"""合作画板 WebSocket 协议常量（v2）。"""

PROTOCOL_VERSION = 2

DEFAULT_BOARD_ID = "b_default"
DEFAULT_LAYER_ID = "l_default"
DEFAULT_BG_LAYER_ID = "l_background"
MAX_BOARDS_PER_ROOM = 20
MAX_LAYERS_PER_BOARD = 20
MAX_PLAYERS_PER_ROOM = 30
DISCONNECT_GRACE_SECONDS = 30
BOARD_CREATE_COOLDOWN_SEC = 60
BOARD_CREATE_OWNER_COOLDOWN_SEC = 3
